version: '3'

env:
  CGO_ENABLED: 0

tasks:
  default:
    deps:
      - all

  all:
    desc: 'Build and test everything'
    deps:
      - build
      - test

  build:
    desc: 'Build all components'
    deps:
      - build:bin
      - build:readme

  build:bin:
    desc: 'Build all binaries'
    deps:
      - build:age-edit

  build:age-edit:
    desc: 'Build the age-edit binary'
    run: once
    cmds:
      - go build -trimpath
    sources:
      - '*.go'
    generates:
      - age-edit{{exeExt}}

  build:readme:
    desc: 'Update the usage section in "README.md" with current help'
    run: once
    deps:
      - build:age-edit
    cmds:
      - go run ./script/readme ./age-edit --help
    env:
      AGE_EDIT_EDITOR: vi
    sources:
      - main.go
      - script/readme/main.go
    generates:
      - README.md

  check:
    desc: 'Build, lint, and test everything'
    deps:
      - build
      - lint
      - test

  clean:
    desc: 'Clean up binaries'
    cmds:
      - rm -f age-edit{{exeExt}}

  lint:
    desc: 'Run golangci-lint'
    cmds:
      - golangci-lint run

  test:
    desc: 'Run tests'
    deps:
      - build:age-edit
    cmds:
      - go test ./...
