version: '3'

env:
  CGO_ENABLED: 0

tasks:
  default:
    deps:
      - all

  all:
    desc: 'Build and test everything'
    deps:
      - build
      - test

  build:
    desc: 'Build all components'
    deps:
      - build-age-edit
      - build-readme

  build-age-edit:
    desc: 'Build the age-edit executable'
    cmds:
      - cmd: go build -trimpath
    sources:
      - '*.go'
    generates:
      - age-edit

  build-readme:
    desc: 'Update the usage section in "README.md" with current help'
    deps:
      - build-age-edit
    cmds:
      - go run ./script/readme ./age-edit --help
    env:
      AGE_EDIT_EDITOR: vi
    status:
      - main.go
    generates:
      - README.md

  check:
    desc: 'Build, lint, and test everything'
    deps:
      - build
      - lint
      - test

  clean:
    desc: 'Clean up executables'
    cmds:
      - rm -f age-edit{{exeExt}}

  lint:
    desc: 'Run golangci-lint'
    cmds:
      - golangci-lint run

  test:
    desc: 'Run tests'
    deps:
      - build-age-edit
    cmds:
      - go test ./...
