name: Merge upstream changes

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  merge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout/@v4

      - name: Merge upstream
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '<>'
          git config --global pull.rebase false

          git pull --unshallow

          git pull --no-edit https://github.com/dbohdan/age-edit.git
          git push
